# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Download and Install Terraform.
    wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
    unzip terraform_0.11.14_linux_amd64.zip
    echo Download and Install Vault.
    wget https://releases.hashicorp.com/vault/1.3.2/vault_1.3.2_linux_amd64.zip
    unzip vault_1.3.2_linux_amd64.zip
    echo Running Terraform Apply.
    cd student
    ../terraform init
    echo Workaround dependancy issue
    mv helmvault.tf helmvault.tf.bak
    ../terraform apply -auto-approve
    mv helmvault.tf.bak helmvault.tf
    ../terraform apply -auto-approve
  displayName: 'Run Terraform Apply'
